;
; Class file 'D:\VXODK\PROJECTS\SOM\vxrexx.cls'
;

version 101
load somobj.cls
load core.cls
load visible.cls
load submenu.cls
load menubar.cls
load appobj.cls
load screen.cls
load menuit.cls
load primiti.cls
load manager.cls
load window.cls
load group.cls
load mle.cls
load button.cls
load listbox.cls
load entryfl.cls
load combo.cls
load desctxt.cls
load pictbox.cls
load spin.cls
load splitba.cls
load combobx.cls
load dropdn.cls
load pbutton.cls
load checkbx.cls
load rbutton.cls
load irbutn.cls
load ipbutn.cls


;
; End of class file
;
